title: Kranken and I
email: aitch0083@gmail.com
description: A small project to keep me occupied
url: "https://aitch0083.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github: https://github.com/aitch0083/aitch0083.github.io
github_username:  aitch0083
about: Taiwanese. Live abroad

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

enableTags: true
tagarray: []